backend:
  name: git-gateway
  repo: RedCiudadana/JusticiaPedia4.0
  branch: main
  identity_url: https://auth.decapbridge.com/sites/03708892-f082-4e37-a2ca-6e4c00e54edd
  gateway_url: https://gateway.decapbridge.com

  commit_messages:
    create: Create {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    update: Update {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    delete: Delete {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    uploadMedia: Upload “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    deleteMedia: Delete “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    openAuthoring: Message {{message}} - {{author-name}} <{{author-login}}> via DecapBridge

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "blogs"
    label: "Blogs"
    folder: "src/content/blogs"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string", required: true }
      - { label: "Subtítulo", name: "subtitulo", widget: "string", required: true }
      - { label: "Imagen de Thumbnail", name: "thumbnail", widget: "image", required: true }
      - { label: "Fecha", name: "fecha", widget: "datetime", required: true }
      - { label: "Duración de lectura (minutos)", name: "duracion_lectura", widget: "number", required: true, value_type: "int" }
      - { label: "Autor", name: "autor", widget: "string", required: true }
      - { label: "Texto del blog", name: "body", widget: "markdown", required: true }
      - { label: "Galería de imágenes y videos", name: "media", widget: "list", required: false, fields: [
          { label: "Tipo", name: "tipo", widget: "select", options: ["imagen", "video"], required: true },
          { label: "Archivo", name: "archivo", widget: "image", required: true },
          { label: "Descripción", name: "descripcion", widget: "string", required: false }
        ] }
